name: Metrics - Main

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate-main-metrics:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: Call shared setup
        uses: ./.github/workflows/setup-common.yml

      - name: Generate main metrics
        uses: lowlighter/metrics@latest
        with:
          github_token: ${{ secrets.METRICS_TOKEN }}
          user: ChristopherAlphonse
          base: header, activity, community, repositories, metadata
          filename: metrics-main.svg
          template: classic
          base_indepth: yes
          base_hireable: yes

      - name: Commit metrics
        run: |
          git add metrics-main.svg
          git commit -m "Update main metrics image" || echo "No changes to commit"
          git push
