name: Setup Common

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.checkout.outputs.repo-path }}
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure jq is installed
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y jq
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
